version: "3.8"

services:
  sourcegraph:
    image: sourcegraph/server:3.27.1
    ports:
      - 7080:7080
      - 2633:2633
      - 443:7443
    environment:
      # ディスク容量がこれ以下になるとうまく動かんくなる
      SRC_REPOS_DESIRED_PERCENT_FREE: 5
    volumes:
      - ./data/sourcegraph/config:/etc/sourcegraph
      - ./data/sourcegraph/data:/var/opt/sourcegraph
